apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka-app
spec:
  ports:
    - name: "9092"
      port: 9092
      protocol: TCP
      targetPort: 9092
      nodePort: 31000
  selector:
    app: kafka-app
  type: NodePort
