stages:
  - provision_infrastructure
  - destroy_infrastructure

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

provision_infra:
  stage: provision_infrastructure
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^provision/
  # image:
  #   name: hamza13/sdtd-deployment-env
  #   entrypoint: [""]
  script:
    - echo provisionning infra
    # - ./create.sh

destroy_infra:
  stage: destroy_infrastructure
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^destroy/
  # image:
  #   name: hamza13/sdtd-deployment-env
  #   entrypoint: [""]
  script:
    - echo $CI_COMMIT_MESSAGE
    - echo destroying infra !
    # - ./create.sh
# changed something
