stages:
  - provision_infrastructure
  - destroy_infrastructure

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

provision_infra:
  stage: provision_infrastructure
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^provision/
  image:
    name: hamza13/sdtd-deployment-env
    entrypoint: [""]
  script:
    - echo provisionning infra
    - cd app
    - echo $GCE_CREDENTIALS > adc.json
    - source /root/.bashrc
    - gcloud compute instances list --filter="(tags.items:bastion)"
    - exit 1
    - bash ./create.sh

destroy_infra:
  stage: destroy_infrastructure
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^destroy/
  image:
    name: hamza13/sdtd-deployment-env
    entrypoint: [""]
  script:
    - echo destroying infra
    - cd app
    - echo $GCE_CREDENTIALS > adc.json
    - bash ./cleanup.sh
