apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-nfs-pvc-cassandra-new-new
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
