- hosts: controller-0
  remote_user: root
  tasks:
    - name: copy rbac-setup script
      copy:
        src: /root/app/08-kube-controller/rbac-setup.sh
        dest: /root/rbac-setup.sh
        owner: root
        group: root
        mode: 0744
    - name: copy admin kube config config
      copy:
        src: /root/app/05-kubeconfig/admin.kubeconfig
        dest: /etc/kubernetes/config/admin.kubeconfig
    - name: waiting for kube to start
      pause:
        seconds: 40
    - name: Setup RBAC
      command: /root/rbac-setup.sh
