- hosts: controller-0
  become: true
  vars:
    nfs_server_ip: "{{ lookup('env','nfs_server_ip') }}"
  tasks:
    - name: install help repo
      shell: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    - name: install helm chart for nfs
      shell: helm upgrade --install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --set nfs.server={{ nfs_server_ip }} --set nfs.path=/data/nfs1 --set storageClass.onDelete=true --set storageClass.volumeBindingMode=WaitForFirstConsumer
    - name: set new storageclass as default
      shell: |
        kubectl patch storageclass nfs-client -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
